dependencies:
  - cachetools
  - cytoolz
  - ipython
  - matplotlib
  - more-itertools
  - networkx
  - numba
  - numpy
  - pandas
  - python
  - rich
  - scikits.odes
  - scipy
  - sundials
  - dask
  - yaml
