dependencies:
  - cachetools
  - cytoolz
  - graphviz
  - ipython
  - matplotlib
  - more-itertools
  - numba
  - numpy
  - pandas
  - python
  - rich
  - scikits.odes
  - scipy
  - sundials
  - dask
  - yaml
  - jupyter
  - mathjax
  - matplotlib
  - nbsphinx
  - networkx
  - numpydoc
  - sphinx
  - sphinx_rtd_theme
  - hypothesis
  - pytest
